import type { RealtimeChannel, RealtimePostgresChangesPayload } from "@supabase/supabase-js";
import { isSupabaseConfigured, supabase } from "@/lib/supabase";
import * as repo from "@/database/repository";
import { notifySyncListeners } from "@/lib/sync";

/**
 * Realtime synchronization status for Supabase WebSocket connection.
 */
export type RealtimeSyncStatus = "connecting" | "connected" | "disconnected" | "error" | "disabled";

export interface RealtimeSubscriptionOptions {
  userId: string;
  onStatusChange?: ((status: RealtimeSyncStatus) => void) | undefined;
  /** Optional custom tables to subscribe to in addition to cadence_sync_records */
  additionalTables?: string[] | undefined;
}

export type RealtimeStatusListener = (status: RealtimeSyncStatus) => void;

// ── In-Memory State & Client Tracking ────────────────────────────────────────

let localClientId: string | null = null;
let currentStatus: RealtimeSyncStatus = "disconnected";
let activeChannel: RealtimeChannel | null = null;
let activeUserId: string | null = null;
let updateBatchTimeout: number | undefined;

const statusListeners = new Set<RealtimeStatusListener>();

/**
 * Cache of recently pushed mutations from this client.
 * Keys are formatted as `${store}:${id}` and `${store}:${id}:${updatedAt}`.
 * Prevents echo loops and duplicate UI updates when the Postgres CDC event
 * bounces back from Supabase over the WebSocket.
 */
const recentLocalPushes = new Map<string, number>();
const RECENT_PUSH_TTL_MS = 60_000; // 60 seconds TTL

/**
 * Returns a persistent unique identifier for this client session.
 * Used to stamp all outgoing records so that incoming Realtime events
 * generated by this specific browser tab can be dropped immediately.
 */
export function getLocalClientId(): string {
  if (localClientId) return localClientId;

  if (typeof window !== "undefined" && window.sessionStorage) {
    try {
      const stored = window.sessionStorage.getItem("cadence_client_id");
      if (stored) {
        localClientId = stored;
        return stored;
      }
    } catch {
      // Storage access may fail in strict private windows
    }
  }

  const generated =
    typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
      ? crypto.randomUUID()
      : `client-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 9)}`;

  localClientId = generated;

  if (typeof window !== "undefined" && window.sessionStorage) {
    try {
      window.sessionStorage.setItem("cadence_client_id", generated);
    } catch {
      // Ignore sessionStorage exceptions
    }
  }

  return generated;
}

/**
 * Records that a local mutation was pushed to Supabase by this client.
 * When the Realtime WebSocket receives the Postgres change event,
 * it verifies this cache to prevent duplicate state updates and infinite loops.
 */
export function trackLocalPush(store: string, id: string, updatedAt?: string): void {
  const now = Date.now();
  recentLocalPushes.set(`${store}:${id}`, now);
  if (updatedAt) {
    recentLocalPushes.set(`${store}:${id}:${updatedAt}`, now);
  }

  // Periodic pruning of stale entries
  if (recentLocalPushes.size > 250) {
    for (const [key, timestamp] of recentLocalPushes.entries()) {
      if (now - timestamp > RECENT_PUSH_TTL_MS) {
        recentLocalPushes.delete(key);
      }
    }
  }
}

/**
 * Checks whether an incoming record was pushed by this client recently.
 */
export function isRecentLocalPush(store: string, id: string, updatedAt?: string): boolean {
  const now = Date.now();
  if (updatedAt) {
    const time = recentLocalPushes.get(`${store}:${id}:${updatedAt}`);
    if (time && now - time < RECENT_PUSH_TTL_MS) return true;
  }
  const generalTime = recentLocalPushes.get(`${store}:${id}`);
  if (generalTime && now - generalTime < RECENT_PUSH_TTL_MS) return true;
  return false;
}

// ── Status Subscription ──────────────────────────────────────────────────────

export function getRealtimeStatus(): RealtimeSyncStatus {
  if (!isSupabaseConfigured) return "disabled";
  return currentStatus;
}

export function subscribeToRealtimeStatus(listener: RealtimeStatusListener): () => void {
  statusListeners.add(listener);
  listener(getRealtimeStatus());
  return () => {
    statusListeners.delete(listener);
  };
}

function setStatus(nextStatus: RealtimeSyncStatus): void {
  if (currentStatus === nextStatus) return;
  currentStatus = nextStatus;
  for (const listener of statusListeners) {
    try {
      listener(nextStatus);
    } catch (error) {
      console.error("Error in realtime status listener:", error);
    }
  }
}

// ── UI Update Scheduling ─────────────────────────────────────────────────────

/**
 * Batches incoming Realtime change notifications over a short window (35ms).
 * When multiple records (e.g. routine steps or habits) arrive in a single burst,
 * all records are written to IndexedDB first and a single UI state refresh is fired.
 */
function scheduleBatchedUiUpdate(): void {
  if (typeof window === "undefined") {
    notifySyncListeners();
    return;
  }

  if (updateBatchTimeout !== undefined) {
    window.clearTimeout(updateBatchTimeout);
  }

  updateBatchTimeout = window.setTimeout(() => {
    updateBatchTimeout = undefined;
    notifySyncListeners();
  }, 35);
}

// ── Event Processing ─────────────────────────────────────────────────────────

/**
 * Processes incoming Postgres changes delivered via Supabase WebSockets.
 * Supports INSERT, UPDATE, and DELETE events.
 */
export async function processPostgresChange(
  payload: RealtimePostgresChangesPayload<Record<string, unknown>>,
  authenticatedUserId: string,
): Promise<void> {
  const eventType = payload.eventType;
  const newRow = payload.new as Record<string, unknown> | null;
  const oldRow = payload.old as Record<string, unknown> | null;
  const activeRow = (newRow && Object.keys(newRow).length > 0 ? newRow : oldRow) ?? {};

  // 1. Strict Security Check: Verify record belongs strictly to authenticated user
  const rowUserId = activeRow["user_id"];
  if (rowUserId && rowUserId !== authenticatedUserId) {
    return;
  }

  // 2. Extract store name, record id, payload data, timestamp, and delete status
  let store: string = "";
  let id: string = "";
  let data: Record<string, unknown> | null = null;
  const updatedAt: string = (activeRow["updated_at"] as string) || new Date().toISOString();
  const isDeleted = eventType === "DELETE" || Boolean(activeRow["deleted"]);

  if (payload.table === "cadence_sync_records") {
    store = (activeRow["store_name"] as string) || "";
    id = (activeRow["record_id"] as string) || "";
    data = (newRow?.["data"] as Record<string, unknown>) ?? null;
  } else if (payload.table === "habits") {
    store = "habits";
    id = (activeRow["id"] as string) || "";
    data = newRow ? { ...newRow } : null;
  } else if (payload.table === "progress" || payload.table === "habit_logs") {
    store = "habitLogs";
    id = (activeRow["id"] as string) || "";
    data = newRow ? { ...newRow } : null;
  } else {
    store = payload.table;
    id = (activeRow["id"] as string) || "";
    data = newRow ? { ...newRow } : null;
  }

  if (!store || !id) return;

  // 3. Echo & Infinite Loop Prevention:
  // Check if the change originated from THIS local browser tab
  const originClientId = typeof data?.["_clientId"] === "string" ? data["_clientId"] : undefined;
  const isSelfClient = originClientId && originClientId === getLocalClientId();
  const isSelfRecentPush = isRecentLocalPush(store, id, updatedAt);

  if (isSelfClient || isSelfRecentPush) {
    // This is an echo of our own mutation that we already applied optimistically.
    // Confirm it locally by clearing the pending_sync flag, without triggering a re-render or push.
    if (!isDeleted && data) {
      void repo.clearPendingSyncFlag(
        store as Parameters<typeof repo.clearPendingSyncFlag>[0],
        id,
        data as repo.SyncableRecord,
      );
    } else if (isDeleted) {
      void repo.clearTombstone(store, id);
    }
    return; // Drop echo cleanly, NO loop, NO duplicate UI update
  }

  // 4. Optimistic Conflict Resolution:
  // Protect any local un-synced edits currently pending on this device
  try {
    const localRecords = await repo.getSyncRecords();
    const local = localRecords.find((r) => r.store === store && r.id === id);

    if (local) {
      // If local record has pending unsaved changes and local timestamp is >= remote, preserve local
      if (local.data?.pending_sync === true && local.updatedAt >= updatedAt) {
        return;
      }
      // If local data is already up-to-date with identical or newer timestamp, skip
      if (local.updatedAt >= updatedAt && !isDeleted) {
        return;
      }
    }

    // 5. Apply remote change to local IndexedDB repository
    // mergeSyncRecord uses idb.put directly with synced: true; it does NOT call write() or pushPendingRecords().
    const syncRecord: repo.SyncRecord = {
      store,
      id,
      data: isDeleted ? null : (data as repo.SyncableRecord),
      updatedAt,
      deleted: isDeleted,
    };

    await repo.mergeSyncRecord(syncRecord);

    // Update last sync timestamp if remote event is newer
    const lastSync = await repo.getLastSyncTimestamp();
    if (updatedAt > lastSync) {
      await repo.setLastSyncTimestamp(updatedAt);
    }

    // 6. Dynamically update local React state / UI immediately without page reload
    scheduleBatchedUiUpdate();
  } catch (error) {
    console.error(`Failed to process realtime Postgres change for ${store}:${id}:`, error);
  }
}

// ── Subscription Management ──────────────────────────────────────────────────

/**
 * Sets up Supabase Realtime subscriptions using `supabase.channel()` to listen
 * for INSERT, UPDATE, and DELETE Postgres events strictly for the authenticated user.
 *
 * Returns a teardown function that cleans up the channel to prevent memory leaks.
 */
export function setupRealtimeSubscription(options: RealtimeSubscriptionOptions): () => void {
  const { userId, onStatusChange, additionalTables = [] } = options;

  if (!isSupabaseConfigured) {
    setStatus("disabled");
    onStatusChange?.("disabled");
    return () => {};
  }

  if (!userId) {
    setStatus("disconnected");
    onStatusChange?.("disconnected");
    return () => {};
  }

  // Return existing teardown if already active for this exact user
  if (activeChannel && activeUserId === userId) {
    return cleanupRealtimeSubscription;
  }

  // Clean up any stale subscription for a previous user
  if (activeChannel) {
    cleanupRealtimeSubscription();
  }

  activeUserId = userId;
  setStatus("connecting");
  onStatusChange?.("connecting");

  // Create isolated Realtime channel scoped to user ID
  const channelName = `cadence:realtime:${userId}`;
  const channel = supabase.channel(channelName);

  // 1. Listen for INSERT, UPDATE, and DELETE on the primary sync records table
  // Filter strictly by authenticated user ID
  channel
    .on(
      "postgres_changes",
      {
        event: "INSERT",
        schema: "public",
        table: "cadence_sync_records",
        filter: `user_id=eq.${userId}`,
      },
      (payload) => void processPostgresChange(payload, userId),
    )
    .on(
      "postgres_changes",
      {
        event: "UPDATE",
        schema: "public",
        table: "cadence_sync_records",
        filter: `user_id=eq.${userId}`,
      },
      (payload) => void processPostgresChange(payload, userId),
    )
    .on(
      "postgres_changes",
      {
        event: "DELETE",
        schema: "public",
        table: "cadence_sync_records",
        filter: `user_id=eq.${userId}`,
      },
      (payload) => void processPostgresChange(payload, userId),
    );

  // 2. Listen on any additional user-specified tables (e.g. habits, progress) if present
  for (const table of additionalTables) {
    channel
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table,
          filter: `user_id=eq.${userId}`,
        },
        (payload) => void processPostgresChange(payload, userId),
      )
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table,
          filter: `user_id=eq.${userId}`,
        },
        (payload) => void processPostgresChange(payload, userId),
      )
      .on(
        "postgres_changes",
        {
          event: "DELETE",
          schema: "public",
          table,
          filter: `user_id=eq.${userId}`,
        },
        (payload) => void processPostgresChange(payload, userId),
      );
  }

  // 3. Subscribe and monitor channel lifecycle
  channel.subscribe((status, err) => {
    if (err) {
      console.warn("Realtime subscription notice:", err);
    }

    if (status === "SUBSCRIBED") {
      setStatus("connected");
      onStatusChange?.("connected");
    } else if (status === "CLOSED") {
      setStatus("disconnected");
      onStatusChange?.("disconnected");
    } else if (status === "CHANNEL_ERROR" || status === "TIMED_OUT") {
      setStatus("error");
      onStatusChange?.("error");
    }
  });

  activeChannel = channel;

  return cleanupRealtimeSubscription;
}

/**
 * Tears down the active Realtime subscription and removes the channel from Supabase.
 * Prevents memory leaks on component unmount or session termination.
 */
export function cleanupRealtimeSubscription(): void {
  if (activeChannel) {
    const channelToClose = activeChannel;
    activeChannel = null;
    activeUserId = null;
    void supabase.removeChannel(channelToClose);
    setStatus("disconnected");
  }
}
