import {
  Dumbbell,
  Droplets,
  Footprints,
  Code2,
  BookOpen,
  Sparkles,
  Moon,
  ShieldCheck,
  CalendarCheck,
  PenTool,
  Globe,
  Pill,
  PhoneOff,
  Wallet,
  Heart,
  type LucideIcon,
} from "lucide-react";

export interface HabitTemplate {
  id: string;
  name: string;
  description: string;
  category:
    | "Fitness"
    | "Focus"
    | "Health"
    | "Productivity"
    | "Academics"
    | "Programming"
    | "Finance"
    | "Mental Health"
    | "Digital Wellbeing";
  type: "boolean" | "counter" | "timer";
  target: number;
  unit: string;
  iconName: string;
  colorName: string;
  colorHex: string;
}

/** Lucide components for template chips (iconName → component). */
export const TEMPLATE_ICONS: Record<string, LucideIcon> = {
  Dumbbell,
  Droplets,
  Footprints,
  Code2,
  BookOpen,
  Sparkles,
  Moon,
  ShieldCheck,
  CalendarCheck,
  PenTool,
  Globe,
  Pill,
  PhoneOff,
  Wallet,
  Heart,
};

// Curated preset templates for quick onboarding
export const HABIT_TEMPLATES: HabitTemplate[] = [
  {
    id: "workout-preset",
    name: "Morning Workout",
    description: "Quick bodyweight workout session",
    category: "Fitness",
    type: "counter",
    target: 30,
    unit: "reps",
    iconName: "Dumbbell",
    colorName: "rose",
    colorHex: "#F43F5E",
  },
  {
    id: "water-preset",
    name: "Stay Hydrated",
    description: "Track daily water consumption",
    category: "Fitness",
    type: "counter",
    target: 8,
    unit: "glasses",
    iconName: "Droplets",
    colorName: "sky",
    colorHex: "#0284C7",
  },
  {
    id: "deep-work-preset",
    name: "Deep Focus Session",
    description: "Distraction-free learning and problem-solving",
    category: "Focus",
    type: "timer",
    target: 45,
    unit: "min",
    iconName: "Code2",
    colorName: "violet",
    colorHex: "#8B5CF6",
  },
  {
    id: "reading-preset",
    name: "Read 20 Minutes",
    description: "Build a consistent daily reading routine",
    category: "Focus",
    type: "timer",
    target: 20,
    unit: "min",
    iconName: "BookOpen",
    colorName: "amber",
    colorHex: "#F59E0B",
  },
  {
    id: "sleep-preset",
    name: "Consistent Sleep",
    description: "Be in bed before midnight",
    category: "Health",
    type: "boolean",
    target: 1,
    unit: "night",
    iconName: "Moon",
    colorName: "indigo",
    colorHex: "#6366F1",
  },
  {
    id: "planning-preset",
    name: "Plan Tomorrow",
    description: "Review priorities before heading to bed",
    category: "Productivity",
    type: "boolean",
    target: 1,
    unit: "plan",
    iconName: "CalendarCheck",
    colorName: "fuchsia",
    colorHex: "#D946EF",
  },
  {
    id: "journal-preset",
    name: "Daily Journaling",
    description: "Write down thoughts and reflect on the day",
    category: "Focus",
    type: "timer",
    target: 15,
    unit: "min",
    iconName: "PenTool",
    colorName: "teal",
    colorHex: "#14B8A6",
  },
  {
    id: "language-preset",
    name: "Learn a Language",
    description: "Practice vocabulary and grammar",
    category: "Focus",
    type: "timer",
    target: 20,
    unit: "min",
    iconName: "Globe",
    colorName: "sky",
    colorHex: "#0EA5E9",
  },
  {
    id: "vitamins-preset",
    name: "Take Vitamins",
    description: "Daily supplements and vitamins",
    category: "Health",
    type: "boolean",
    target: 1,
    unit: "dose",
    iconName: "Pill",
    colorName: "lime",
    colorHex: "#84CC16",
  },
  {
    id: "yoga-preset",
    name: "Yoga & Stretch",
    description: "Improve flexibility and relax muscles",
    category: "Fitness",
    type: "timer",
    target: 20,
    unit: "min",
    iconName: "Heart",
    colorName: "pink",
    colorHex: "#EC4899",
  },
  {
    id: "detox-preset",
    name: "Digital Detox",
    description: "No social media or screens before bed",
    category: "Productivity",
    type: "boolean",
    target: 1,
    unit: "day",
    iconName: "PhoneOff",
    colorName: "slate",
    colorHex: "#64748B",
  },
  {
    id: "savings-preset",
    name: "No Spend Day",
    description: "Avoid unnecessary purchases today",
    category: "Productivity",
    type: "boolean",
    target: 1,
    unit: "day",
    iconName: "Wallet",
    colorName: "emerald",
    colorHex: "#10B981",
  },
  {
    id: "flashcards-preset",
    name: "Review Flashcards",
    description: "Strengthen recall with a focused study block",
    category: "Academics",
    type: "counter",
    target: 25,
    unit: "cards",
    iconName: "BookOpen",
    colorName: "indigo",
    colorHex: "#6366F1",
  },
  {
    id: "coding-practice-preset",
    name: "Practice Coding",
    description: "Build a small programming habit every day",
    category: "Programming",
    type: "timer",
    target: 30,
    unit: "min",
    iconName: "Code2",
    colorName: "sky",
    colorHex: "#0EA5E9",
  },
  {
    id: "coursework-preset",
    name: "Complete Coursework",
    description: "Make steady progress on your current class work",
    category: "Academics",
    type: "timer",
    target: 45,
    unit: "min",
    iconName: "CalendarCheck",
    colorName: "violet",
    colorHex: "#8B5CF6",
  },
  {
    id: "budget-check-preset",
    name: "Check Spending",
    description: "Review today's purchases and stay aware of your budget",
    category: "Finance",
    type: "boolean",
    target: 1,
    iconName: "Wallet",
    colorName: "emerald",
    colorHex: "#10B981",
  },
  {
    id: "gratitude-preset",
    name: "Write Three Good Things",
    description: "Notice small wins and moments worth remembering",
    category: "Mental Health",
    type: "counter",
    target: 3,
    unit: "things",
    iconName: "Sparkles",
    colorName: "amber",
    colorHex: "#F59E0B",
  },
  {
    id: "breathing-preset",
    name: "Mindful Breathing",
    description: "Create a short pause to reset your nervous system",
    category: "Mental Health",
    type: "timer",
    target: 10,
    unit: "min",
    iconName: "Heart",
    colorName: "teal",
    colorHex: "#14B8A6",
  },
  {
    id: "phone-free-morning-preset",
    name: "Phone-Free Morning",
    description: "Start the day before opening social apps",
    category: "Digital Wellbeing",
    type: "boolean",
    target: 1,
    unit: "morning",
    iconName: "PhoneOff",
    colorName: "slate",
    colorHex: "#64748B",
  },
  {
    id: "language-vocabulary-preset",
    name: "Practice Vocabulary",
    description: "Learn a small set of useful words consistently",
    category: "Academics",
    type: "counter",
    target: 15,
    unit: "words",
    iconName: "Languages",
    colorName: "sky",
    colorHex: "#0284C7",
  },
  {
    id: "medication-preset",
    name: "Take Medication",
    description: "Keep an important health routine consistent",
    category: "Health",
    type: "boolean",
    target: 1,
    unit: "dose",
    iconName: "Pill",
    colorName: "rose",
    colorHex: "#F43F5E",
  },
];
